# Generated by Django 2.1.2 on 2018-11-01 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpinResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('resultado', models.TextField()),
                ('apuesta', models.IntegerField(default=8)),
            ],
        ),
    ]
