# Generated by Django 2.1.2 on 2018-11-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miaurulet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinresult',
            name='user_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
